//! Real timer-preempted register/SIMD/x87/flags fixture. Never yields until checked.
use core::arch::naked_asm;
static mut SAVED_SP:u64=0;
#[repr(C,align(16))]
struct Aligned([u8;16]);
static ONES:Aligned=Aligned([0xff;16]);
/// Never returns: the scheduler must preempt this loop and preserve its state.
/// The private Report syscall validates that real timer preemptions occurred.
#[unsafe(naked)]
pub unsafe extern "sysv64" fn exercise()->!{
    naked_asm!(
        "mov qword ptr [rip + {saved}], rsp",
        "sub rsp, 16",
        "mov dword ptr [rsp], 0x3f80",
        "ldmxcsr [rsp]",
        "fld1",
        "add rsp, 16",
        "mov rbx, 4369",
        "mov rdx, 8738",
        "mov rsi, 13107",
        "mov rdi, 17476",
        "mov rbp, 21845",
        "mov r8, 26214",
        "mov r9, 30583",
        "mov r10, 34952",
        "mov r11, 39321",
        "mov r12, 43690",
        "mov r13, 48059",
        "mov r14, 52428",
        "mov r15, 56797",
        "pcmpeqb xmm0, xmm0",
        "pcmpeqb xmm1, xmm1",
        "pcmpeqb xmm2, xmm2",
        "pcmpeqb xmm3, xmm3",
        "pcmpeqb xmm4, xmm4",
        "pcmpeqb xmm5, xmm5",
        "pcmpeqb xmm6, xmm6",
        "pcmpeqb xmm7, xmm7",
        "pcmpeqb xmm8, xmm8",
        "pcmpeqb xmm9, xmm9",
        "pcmpeqb xmm10, xmm10",
        "pcmpeqb xmm11, xmm11",
        "pcmpeqb xmm12, xmm12",
        "pcmpeqb xmm13, xmm13",
        "pcmpeqb xmm14, xmm14",
        "pcmpeqb xmm15, xmm15",
        "mov rax, 61166",
        "std",
        "stc",
        "mov rcx, 10000000",
        "2:",
        "dec rcx",
        "jne 2b",
        "push rax",
        "pushfq",
        "pop rax",
        "and eax, 0x401",
        "cmp eax, 0x401",
        "jne 9f",
        "pop rax",
        "cmp rax, 61166",
        "jne 9f",
        "std",
        "stc",
        "mov rcx, 65535",
        "mov r15, 56798",
        "mov rax, 10000000",
        "4:",
        "dec rax",
        "jne 4b",
        "pushfq",
        "pop rax",
        "and eax, 0x401",
        "cmp eax, 0x401",
        "jne 9f",
        "cld",
        "cmp rcx, 65535",
        "jne 9f",
        "cmp rbx, 4369",
        "jne 9f",
        "cmp rdx, 8738",
        "jne 9f",
        "cmp rsi, 13107",
        "jne 9f",
        "cmp rdi, 17476",
        "jne 9f",
        "cmp rbp, 21845",
        "jne 9f",
        "cmp r8, 26214",
        "jne 9f",
        "cmp r9, 30583",
        "jne 9f",
        "cmp r10, 34952",
        "jne 9f",
        "cmp r11, 39321",
        "jne 9f",
        "cmp r12, 43690",
        "jne 9f",
        "cmp r13, 48059",
        "jne 9f",
        "cmp r14, 52428",
        "jne 9f",
        "cmp r15, 56798",
        "jne 9f",
        "cmp rsp, qword ptr [rip + {saved}]",
        "jne 9f",
        "pcmpeqb xmm0, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm0",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm1, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm1",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm2, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm2",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm3, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm3",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm4, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm4",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm5, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm5",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm6, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm6",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm7, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm7",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm8, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm8",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm9, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm9",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm10, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm10",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm11, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm11",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm12, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm12",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm13, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm13",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm14, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm14",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm15, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm15",
        "cmp eax, 65535",
        "jne 9f",
        "sub rsp, 16",
        "stmxcsr [rsp]",
        "cmp dword ptr [rsp], 0x3f80",
        "jne 9f",
        "fistp qword ptr [rsp + 8]",
        "cmp qword ptr [rsp + 8], 1",
        "jne 9f",
        "add rsp, 16",
        "mov r15, 56797",
        "fld1",
        "xor eax,eax",
        "std",
        "stc",
        "int 0x80",
        "push rax",
        "pushfq",
        "pop rax",
        "and eax, 0x401",
        "cmp eax, 0x401",
        "jne 9f",
        "pop rax",
        "test rax,rax",
        "jne 9f",
        "cld",
        "cmp rbx, 4369",
        "jne 9f",
        "cmp rdx, 8738",
        "jne 9f",
        "cmp rsi, 13107",
        "jne 9f",
        "cmp rdi, 17476",
        "jne 9f",
        "cmp rbp, 21845",
        "jne 9f",
        "cmp r8, 26214",
        "jne 9f",
        "cmp r9, 30583",
        "jne 9f",
        "cmp r10, 34952",
        "jne 9f",
        "cmp r11, 39321",
        "jne 9f",
        "cmp r12, 43690",
        "jne 9f",
        "cmp r13, 48059",
        "jne 9f",
        "cmp r14, 52428",
        "jne 9f",
        "cmp r15, 56797",
        "jne 9f",
        "cmp rcx, 65535",
        "jne 9f",
        "cmp rsp, qword ptr [rip + {saved}]",
        "jne 9f",
        "pcmpeqb xmm0, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm0",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm1, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm1",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm2, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm2",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm3, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm3",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm4, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm4",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm5, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm5",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm6, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm6",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm7, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm7",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm8, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm8",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm9, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm9",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm10, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm10",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm11, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm11",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm12, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm12",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm13, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm13",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm14, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm14",
        "cmp eax, 65535",
        "jne 9f",
        "pcmpeqb xmm15, xmmword ptr [rip + {ones}]",
        "pmovmskb eax, xmm15",
        "cmp eax, 65535",
        "jne 9f",
        "sub rsp,16",
        "stmxcsr [rsp]",
        "cmp dword ptr [rsp],0x3f80",
        "jne 9f",
        "fistp qword ptr [rsp+8]",
        "cmp qword ptr [rsp+8],1",
        "jne 9f",
        "add rsp,16",
        "fld1",
        "mov rdi,4294967297",
        "mov rsi,6291456",
        "mov rdx,144",
        "mov r10,1",
        "mov eax,2",
        "std",
        "stc",
        "int 0x80",
        "push rax",
        "pushfq",
        "pop rax",
        "and eax,0x401",
        "cmp eax,0x401",
        "jne 9f",
        "pop rax",
        "cmp rax,-5",
        "jne 9f",
        "cld",
        "mov rax,4294967297",
        "cmp rdi,rax",
        "jne 9f",
        "cmp rbx,4369",
        "jne 9f",
        "cmp rsi,6291456",
        "jne 9f",
        "cmp rdx,144",
        "jne 9f",
        "cmp rbp,21845",
        "jne 9f",
        "cmp r8,26214",
        "jne 9f",
        "cmp r9,30583",
        "jne 9f",
        "cmp r10,1",
        "jne 9f",
        "cmp r11,39321",
        "jne 9f",
        "cmp r12,43690",
        "jne 9f",
        "cmp r13,48059",
        "jne 9f",
        "cmp r14,52428",
        "jne 9f",
        "cmp r15,56797",
        "jne 9f",
        "cmp rcx,65535",
        "jne 9f",
        "cmp rsp,qword ptr [rip+{saved}]",
        "jne 9f",
        "pcmpeqb xmm0,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm0",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm1,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm1",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm2,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm2",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm3,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm3",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm4,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm4",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm5,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm5",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm6,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm6",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm7,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm7",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm8,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm8",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm9,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm9",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm10,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm10",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm11,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm11",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm12,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm12",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm13,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm13",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm14,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm14",
        "cmp eax,65535",
        "jne 9f",
        "pcmpeqb xmm15,xmmword ptr [rip+{ones}]",
        "pmovmskb eax,xmm15",
        "cmp eax,65535",
        "jne 9f",
        "sub rsp,16",
        "stmxcsr [rsp]",
        "cmp dword ptr [rsp],0x3f80",
        "jne 9f",
        "fistp qword ptr [rsp+8]",
        "cmp qword ptr [rsp+8],1",
        "jne 9f",
        "add rsp,16",
        "mov eax, 4",
        "mov edi, 4",
        "xor esi, esi",
        "xor edx, edx",
        "xor r10d, r10d",
        "int 0x80",
        "test rax, rax",
        "jne 9f",
        "3:",
        "xor eax, eax",
        "int 0x80",
        "jmp 3b",
        "9:",
        "cld",
        "mov eax, 4",
        "mov edi, 255",
        "int 0x80",
        "mov eax, 5",
        "int 0x80",
        "ud2",
        saved=sym SAVED_SP,ones=sym ONES,
    )
}
