"""Causal Modern crypto comparison controller component.
The trusted cloud caller supplies already-confined, inventory-approved adapter
execution and evidence retention. This module grants no image/load/VM authority.
"""
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import sys
import time

MAX_EVIDENCE=16*1024*1024
DEADLINE_SECONDS=1800

class Invalid(ValueError):pass

def _load(name):
    if sys.flags.isolated!=1 or not sys.dont_write_bytecode:
        raise Invalid("isolated no-bytecode controller required")
    path=Path(__file__).resolve().with_name(name+".py")
    if path.is_symlink() or not path.is_file() or path.stat().st_size>128*1024:
        raise Invalid("fixed bounded trusted helper")
    spec=importlib.util.spec_from_file_location("modern_comparison_"+name,path)
    module=importlib.util.module_from_spec(spec)
    # Dataclass helpers need their own fixed module name registered.
    sys.modules[spec.name]=module
    spec.loader.exec_module(module)
    return module

protocol=_load("reference_protocol")
corpus=_load("reference_corpus")

def canonical(value):
    raw=json.dumps(value,sort_keys=True,separators=(",",":"),ensure_ascii=True,
                   allow_nan=False).encode("ascii")+b"\n"
    if len(raw)>MAX_EVIDENCE:raise Invalid("comparison evidence budget")
    return raw

def _tuple(value,implementation):
    if (type(value) is not tuple or len(value)!=4 or
        type(value[0]) is not int or value[0]!=implementation or
        type(value[1]) is not int or type(value[2]) is not bytes or
        type(value[3]) is not bytes):
        raise Invalid("exact adapter result tuple")
    return value

def _wire(run):
    return {"implementation":run[0],"exit_code":run[1],
            "stdout":run[2].hex(),"stderr":run[3].hex()}

def compare_all(execute,retain,*,challenge=False):
    """Run the fixed corpus, optionally with fresh challenges; freeze RAR first.
    execute(implementation_id, immutable_request_bytes) returns the exact
    (id,exit,stdout,stderr) tuple from the reviewed bounded adapter runner.
    retain(fixed_leaf_name, immutable_bytes) durably retains evidence and
    returns its SHA256 only after successful storage, or raises. The caller
    must not acknowledge data it has not retained. Neither callback is
    selected from proposal/guest inputs.
    """
    if not callable(execute) or not callable(retain):
        raise Invalid("trusted controller callbacks")
    if (os.environ.get("GITHUB_ACTIONS")!="true" or
        os.environ.get("GITHUB_REPOSITORY")!="AndyTechCoder/RAR-OS" or
        os.environ.get("GITHUB_EVENT_NAME")!="workflow_dispatch" or
        os.environ.get("GITHUB_REF")!="refs/heads/main" or sys.platform!="linux"):
        raise Invalid("trusted-main cloud comparison only")
    if type(challenge) is not bool:raise Invalid("exact challenge mode")
    # Generated by trusted controller, never proposal/adapter callbacks. Public
    # seed is retained in the frozen envelope for exact later reproduction.
    seed=os.urandom(32) if challenge else None
    if challenge and (type(seed) is not bytes or len(seed)!=32):
        raise Invalid("exact challenge entropy result")
    return _compare(execute,retain,seed)

def _compare(execute,retain,challenge_seed=None):
    # This internal function is exercised with synthetic callbacks in cloud
    # source tests. Production entry is compare_all with the cloud guard.
    deadline=time.monotonic()+DEADLINE_SECONDS
    def budget():
        if time.monotonic()>deadline:raise TimeoutError("comparison deadline")
    def invoke(ident,request):
        budget()
        result=_tuple(execute(ident,request),ident)
        budget()
        parsed=protocol.response(request,*result)
        return result,parsed
    def save(name,value):
        budget()
        raw=canonical(value)
        digest=hashlib.sha256(raw).hexdigest()
        ack=retain(name,raw)
        if type(ack) is not str or ack!=digest:
            raise Invalid("evidence retention acknowledgement")
        budget()
        return digest
    base=corpus.cases()
    if type(base) is not tuple or len(base)!=146 or len({c.name for c in base})!=146:
        raise Invalid("exact base corpus")
    extra=() if challenge_seed is None else corpus.challenge_cases(challenge_seed)
    if len(extra)!=(0 if challenge_seed is None else 20):raise Invalid("challenge case count")
    base=base+extra
    total=288+(36 if extra else 0)
    rows=[]
    for case in base:
        request=protocol.request(case.operation,case.payload)
        result,parsed=invoke(3,request)
        corpus.check_expected(case,parsed.status,parsed.value)
        rows.append((case,request,result,parsed))
    # Inputs depend only on frozen RAR seal output and original fixture data,
    # never on reference outputs. They are not accepted until all seals and
    # derived cases independently agree at the final comparison.
    derived=[]
    for case,request,result,parsed in rows:
        if case.operation==4:
            derived.extend(corpus.open_cases(case,parsed.value))
    if len(derived)!=142+(16 if extra else 0):raise Invalid("exact derived corpus")
    for case in derived:
        request=protocol.request(case.operation,case.payload)
        result,parsed=invoke(3,request)
        corpus.check_expected(case,parsed.status,parsed.value)
        rows.append((case,request,result,parsed))
    if len(rows)!=total or len({row[0].name for row in rows})!=total:
        raise Invalid("complete unique comparison corpus")
    frozen={"schema":"rar-modern-frozen-comparison-v0","cases":[
        {"name":case.name,"request":request.hex(),"expected_status":case.status,
         "expected_value":None if case.value is None else case.value.hex(),
         "rar":_wire(result)}
        for case,request,result,parsed in rows]}
    if extra:
        frozen["schema"]="rar-modern-frozen-comparison-v1"
        frozen["challenge_seed"]=challenge_seed.hex()
        frozen["challenge_base_cases"]=20
    frozen_hash=save("frozen-rar-results.json",frozen)
    # No reference callback occurs above this point. Retention failure aborts.
    compared=[]
    for case,request,result,parsed in rows:
        one,_=invoke(1,request)
        two,_=invoke(2,request)
        agreed=protocol.compare(request,(result,one,two))
        corpus.check_expected(case,agreed.status,agreed.value)
        compared.append({"name":case.name,"request_sha256":hashlib.sha256(request).hexdigest(),
                         "runs":[_wire(run) for run in (result,one,two)]})
    results_hash=save("three-way-results.json",
        {"schema":"rar-modern-three-way-comparison-v1" if extra else "rar-modern-three-way-comparison-v0","frozen_sha256":frozen_hash,
         "cases":compared})
    return {"schema":"rar-modern-comparison-result-v1" if extra else "rar-modern-comparison-result-v0","base_cases":len(base),
            "derived_cases":len(derived),"compared":total,"adapter_invocations":total*3,
            "frozen_sha256":frozen_hash,"results_sha256":results_hash,
            "three_way_agreement":True,"milestone_complete":False}

def replay(frozen_raw,results_raw,claimed,*,challenge=False):
    """Pure retained-byte regeneration; never executes an adapter or reads files.
    The caller must separately bind archive receipt, controller/source and image
    identity. Explicit mode prevents accepting v1 evidence as historical v0.
    """
    import re
    if type(challenge) is not bool:raise Invalid("exact replay mode")
    def parse(raw):
        if type(raw) is not bytes or not 1<=len(raw)<=MAX_EVIDENCE:
            raise Invalid("bounded replay envelope")
        def pairs(items):
            out={}
            for key,value in items:
                if key in out:raise Invalid("duplicate replay key")
                out[key]=value
            return out
        def constant(value):raise Invalid("nonfinite replay JSON")
        try:value=json.loads(raw,object_pairs_hook=pairs,parse_constant=constant)
        except (ValueError,UnicodeError,RecursionError) as error:
            raise Invalid("invalid replay JSON") from error
        if type(value) is not dict or canonical(value)!=raw:
            raise Invalid("canonical replay envelope")
        return value
    frozen=parse(frozen_raw);results=parse(results_raw)
    version="v1" if challenge else "v0"
    fields={"schema","cases"}|({"challenge_seed","challenge_base_cases"} if challenge else set())
    if (set(frozen)!=fields or frozen["schema"]!="rar-modern-frozen-comparison-"+version or
        set(results)!={"schema","cases","frozen_sha256"} or
        results["schema"]!="rar-modern-three-way-comparison-"+version):
        raise Invalid("explicit replay version")
    seed=None;total=324 if challenge else 288
    if challenge:
        value=frozen["challenge_seed"]
        if (type(value) is not str or re.fullmatch("[0-9a-f]{64}",value) is None or
            type(frozen["challenge_base_cases"]) is not int or frozen["challenge_base_cases"]!=20):
            raise Invalid("canonical retained challenge identity")
        seed=bytes.fromhex(value)
    if any(type(obj["cases"]) is not list or len(obj["cases"])!=total for obj in (frozen,results)):
        raise Invalid("exact replay count")
    count=0
    def recorded(implementation,request):
        nonlocal count
        if count>=total*3:raise Invalid("replay invocation bound")
        try:
            if count<total:
                row=frozen["cases"][count];wire=row["rar"]
                if row["request"]!=request.hex():raise Invalid("regenerated request differs")
            else:
                index,which=divmod(count-total,2)
                wire=results["cases"][index]["runs"][which+1]
            if (type(wire) is not dict or set(wire)!={"implementation","exit_code","stdout","stderr"} or
                type(wire["implementation"]) is not int or wire["implementation"]!=implementation or
                type(wire["exit_code"]) is not int):
                raise Invalid("exact replay wire")
            for key in ("stdout","stderr"):
                if (type(wire[key]) is not str or len(wire[key])>2*MAX_EVIDENCE or
                    re.fullmatch("(?:[0-9a-f]{2})*",wire[key]) is None):
                    raise Invalid("canonical replay wire bytes")
            count+=1
            return implementation,wire["exit_code"],bytes.fromhex(wire["stdout"]),bytes.fromhex(wire["stderr"])
        except (KeyError,IndexError,TypeError) as error:
            raise Invalid("malformed replay row") from error
    expected={"frozen-rar-results.json":frozen_raw,"three-way-results.json":results_raw}
    def retain(name,raw):
        if expected.get(name)!=raw:raise Invalid("regenerated envelope differs")
        return hashlib.sha256(raw).hexdigest()
    report=_compare(recorded,retain,seed)
    if count!=total*3 or canonical(claimed)!=canonical(report):
        raise Invalid("complete replay report")
    return report

def self_test():
    import struct
    import unittest
    def output(request,ident,status,value):
        op,_=protocol.parse_request(request)
        return (b"RARMCO00"+bytes((op,status,ident))+bytes(5)+
            struct.pack("<I",len(value))+bytes(4)+hashlib.sha256(request).digest()+
            bytes(8)+value)
    def fixture(seed=None):
        # Synthetic wire data exercises orchestration, never crypto correctness.
        answers={}
        for case in corpus.cases()+(() if seed is None else corpus.challenge_cases(seed)):
            value=case.value
            if value is None:
                _,dn=struct.unpack_from("<HH",case.payload,44)
                value=bytes(dn+16)
            request=protocol.request(case.operation,case.payload)
            answers[request]=(case.status,value)
            if case.operation==4:
                for derived in corpus.open_cases(case,value):
                    answers[protocol.request(derived.operation,derived.payload)]=(derived.status,derived.value)
        events=[];saved={}
        def execute(ident,request):
            events.append(ident)
            status,value=answers[request]
            return (ident,0,output(request,ident,status,value),b"")
        def retain(name,raw):
            events.append(name)
            saved[name]=raw
            return hashlib.sha256(raw).hexdigest()
        return execute,retain,events,saved
    class Tests(unittest.TestCase):
        def test_retained_replay_regenerates_both_versions_without_adapters(self):
            for seed in (None,bytes(range(32))):
                execute,retain,_,saved=fixture(seed)
                report=_compare(execute,retain,seed)
                args=(saved["frozen-rar-results.json"],saved["three-way-results.json"],report)
                self.assertEqual(replay(*args,challenge=seed is not None),report)
                with self.assertRaises(Invalid):replay(*args,challenge=seed is None)
                with self.assertRaises(Invalid):replay(*args,challenge=1)
                wrong=dict(report);wrong["adapter_invocations"]+=1
                with self.assertRaises(Invalid):replay(args[0],args[1],wrong,challenge=seed is not None)
                with self.assertRaises(Invalid):replay(args[0]+b" ",args[1],report,challenge=seed is not None)
        def test_retained_challenge_tampering_is_rejected(self):
            execute,retain,_,saved=fixture(bytes(range(32)))
            report=_compare(execute,retain,bytes(range(32)))
            f=saved["frozen-rar-results.json"];r=saved["three-way-results.json"]
            for mutation in ("seed","bool-count","count","request","rar-identity","name","extra","schema"):
                changed=json.loads(f)
                if mutation=="seed":changed["challenge_seed"]="ff"*32
                elif mutation=="bool-count":changed["challenge_base_cases"]=True
                elif mutation=="count":changed["cases"].pop()
                elif mutation=="request":changed["cases"][0]["request"]="00"
                elif mutation=="rar-identity":changed["cases"][0]["rar"]["implementation"]=True
                elif mutation=="name":changed["cases"][0]["name"]="different"
                elif mutation=="extra":changed["extra"]=None
                else:changed["schema"]="rar-modern-frozen-comparison-v0"
                with self.assertRaises(ValueError):replay(canonical(changed),r,report,challenge=True)
            for mutation in ("reference","hash","count","order"):
                changed=json.loads(r)
                if mutation=="reference":changed["cases"][0]["runs"][1]["implementation"]=2
                elif mutation=="hash":changed["frozen_sha256"]="0"*64
                elif mutation=="count":changed["cases"].pop()
                else:changed["cases"][0],changed["cases"][1]=changed["cases"][1],changed["cases"][0]
                with self.assertRaises(ValueError):replay(f,canonical(changed),report,challenge=True)
            for raw in (b'{"schema":0,"schema":1}',b"[]",b"null",b"{",b"\xff"):
                with self.assertRaises(Invalid):replay(raw,r,report,challenge=True)

        def test_public_challenge_entry_draws_seed_only_after_guard(self):
            seed=bytes(range(32));calls=[]
            keys={"GITHUB_ACTIONS":"true","GITHUB_REPOSITORY":"AndyTechCoder/RAR-OS",
                  "GITHUB_EVENT_NAME":"workflow_dispatch","GITHUB_REF":"refs/heads/main"}
            previous={k:os.environ.get(k) for k in keys};random=os.urandom
            try:
                os.environ.update(keys)
                os.urandom=lambda n:(calls.append(n),seed)[1]
                execute,retain,_,_=fixture(seed)
                self.assertEqual(compare_all(execute,retain,challenge=True)["compared"],324)
                self.assertEqual(calls,[32])
                for bad in (1,None,"true"):
                    with self.assertRaises(Invalid):compare_all(execute,retain,challenge=bad)
                self.assertEqual(calls,[32])
                for bad_seed in (None,True,"x"*32,bytearray(32),bytes(31),bytes(33)):
                    os.urandom=lambda n:bad_seed
                    e,r,events,_=fixture(seed)
                    with self.assertRaises(Invalid):compare_all(e,r,challenge=True)
                    self.assertEqual(events,[])
                os.urandom=lambda n:(calls.append(n),seed)[1]
                os.environ["GITHUB_EVENT_NAME"]="pull_request_target"
                with self.assertRaises(Invalid):compare_all(execute,retain,challenge=True)
                self.assertEqual(calls,[32])
            finally:
                os.urandom=random
                for k,v in previous.items():
                    if v is None:os.environ.pop(k,None)
                    else:os.environ[k]=v
        def test_challenge_batch_is_frozen_before_references_and_reproducible(self):
            seed=bytes(range(32));execute,retain,events,saved=fixture(seed)
            result=_compare(execute,retain,seed)
            self.assertEqual(result["base_cases"],166)
            self.assertEqual(result["derived_cases"],158)
            self.assertEqual(result["adapter_invocations"],972)
            self.assertEqual(events[:324],[3]*324)
            self.assertEqual(events[324],"frozen-rar-results.json")
            self.assertEqual(events[325:-1],[1,2]*324)
            frozen=json.loads(saved["frozen-rar-results.json"])
            self.assertEqual(frozen["schema"],"rar-modern-frozen-comparison-v1")
            self.assertEqual(frozen["challenge_seed"],seed.hex())
            self.assertEqual(len(frozen["cases"]),324)
            e,r,_,second=fixture(seed)
            self.assertEqual(result,_compare(e,r,seed));self.assertEqual(saved,second)
            execute,_,events,_=fixture(seed)
            with self.assertRaises(Invalid):_compare(execute,lambda *_:None,seed)
            self.assertEqual(events,[3]*324)
            for bad in (b"",bytes(31),bytes(33),"x"*32):
                execute,retain,events,_=fixture(seed)
                with self.assertRaises(ValueError):_compare(execute,retain,bad)
                self.assertEqual(events,[])
        def test_all_rar_frozen_before_any_oracle_and_reproducible(self):
            execute,retain,events,saved=fixture()
            result=_compare(execute,retain)
            self.assertEqual(events[:288],[3]*288)
            self.assertEqual(events[288],"frozen-rar-results.json")
            self.assertEqual(events[289:-1],[1,2]*288)
            self.assertEqual(events[-1],"three-way-results.json")
            self.assertEqual(result["compared"],288)
            self.assertFalse(result["milestone_complete"])
            frozen=json.loads(saved["frozen-rar-results.json"])
            self.assertEqual(len({c["name"] for c in frozen["cases"]}),288)
            e2,r2,_,s2=fixture()
            self.assertEqual(result,_compare(e2,r2))
            self.assertEqual(saved,s2)
        def test_retention_failure_prevents_all_oracles(self):
            for bad in (None,True,"0"*64):
                execute,retain,events,saved=fixture()
                with self.assertRaises(Invalid):
                    _compare(execute,lambda name,raw:bad)
                self.assertEqual(events,[3]*288)
        def test_wrong_result_identity_process_failure_and_mismatch_stop(self):
            for kind in ("identity","exit","stderr","mismatch"):
                execute,retain,events,saved=fixture()
                def bad(ident,request):
                    value=execute(ident,request)
                    if ident!=1:return value
                    if kind=="identity":return (2,*value[1:])
                    if kind=="exit":return (1,1,value[2],b"")
                    if kind=="stderr":return (1,0,value[2],b"warning")
                    raw=bytearray(value[2]);raw[-1]^=1
                    return (1,0,bytes(raw),b"")
                with self.assertRaises(ValueError):_compare(bad,retain)
                self.assertIn("frozen-rar-results.json",saved)
                self.assertNotIn("three-way-results.json",saved)
                self.assertLessEqual(len([v for v in events if type(v) is int]),290)
        def test_target_failure_never_reaches_reference_or_retention(self):
            execute,retain,events,saved=fixture()
            def bad(ident,request):
                value=execute(ident,request)
                return (ident,1,value[2],b"")
            with self.assertRaises(ValueError):_compare(bad,retain)
            self.assertEqual(events,[3]);self.assertEqual(saved,{})
        def test_timeout_stops_without_retry(self):
            execute,retain,events,saved=fixture()
            original=time.monotonic
            ticks=iter((0,DEADLINE_SECONDS+1))
            try:
                time.monotonic=lambda:next(ticks)
                with self.assertRaises(TimeoutError):_compare(execute,retain)
            finally:time.monotonic=original
            self.assertEqual(events,[])
        def test_cloud_guard_denies_source_test_context(self):
            # Source CI is pull_request_target/push, not an activation workflow.
            original=os.environ.get("GITHUB_EVENT_NAME")
            try:
                os.environ["GITHUB_EVENT_NAME"]="pull_request_target"
                with self.assertRaises(Invalid):compare_all(lambda *_:None,lambda *_:None)
            finally:
                if original is None:os.environ.pop("GITHUB_EVENT_NAME",None)
                else:os.environ["GITHUB_EVENT_NAME"]=original
    result=unittest.TextTestRunner(verbosity=2).run(unittest.defaultTestLoader.loadTestsFromTestCase(Tests))
    if not result.wasSuccessful():raise SystemExit(1)

if __name__=="__main__":
    if (sys.argv!=[sys.argv[0],"--self-test"] or os.environ.get("CI")!="true" or
        os.environ.get("GITHUB_ACTIONS")!="true" or sys.platform!="linux"):
        raise SystemExit("cloud isolated source-test entrypoint only")
    self_test()
